import '../globals.css';
import type { Metadata } from 'next';
import { Google_Sans, Raleway } from 'next/font/google';
import { ThemeProvider } from '@/lib/theme-provider';
import Providers from '../providers';

const googleSans = Google_Sans({
  variable: '--font-google-sans',
  subsets: ['latin'],
});

const raleway = Raleway({
  variable: '--font-raleway',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Takda',
  description: 'Generated by create next app',
};

const jsonLd = {
  '@context': 'https://schema.org',
  // Add more JSON-LD fields as more as possible
};

export default async function RootLayout({
  children,
  params,
}: LayoutProps<'/[lang]'>) {
  const { lang } = await params;

  return (
    <html
      lang="en"
      suppressHydrationWarning
      data-scroll-behavior="smooth"
      className={`${googleSans.variable} ${raleway.variable} h-full antialiased`}
    >
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body className={`${googleSans.variable} ${raleway.variable} h-full antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem={true}
          disableTransitionOnChange
        >
          <Providers>
          {children}
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
